# Generated by Django 3.1 on 2021-01-17 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('market_values', models.TextField(help_text='This field gonna be saved as a plain text in DB, and it represents a list split by commas')),
            ],
            options={
                'db_table': 'companies',
                'ordering': ['-created_on'],
            },
        ),
    ]
